version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
      - "9000:9000"
    depends_on:
      - clickhouse
    networks:
      - appnet

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/configs/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse/configs/default-user.xml:/etc/clickhouse-server/users.d/default-user.xml
    networks:
      - appnet

networks:
  appnet:
